development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  ssl_params: {
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  }